package com.simulator.logging;

public enum LogEvento {
    INICIO_SIMULACION, FIN_SIMULACION,
    CREAR_PROCESO, SELECCIONAR, EJECUTAR_TICK,
    CAMBIO_ESTADO, SUSPENDER, REANUDAR, TERMINAR_PROCESO,
    CAMBIAR_ALGORITMO, CAMBIO_TICK, IDLE, ERROR
}